steps:
  # Step to list files in the source directory
  - name: 'gcr.io/cloud-builders/bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Listing files in the source directory:" && ls -R .'


  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", ".", "gs://medicine-bot-445314_cloudbuild/"]

options:
  logging: CLOUD_LOGGING_ONLY
