# Generated by Django 3.2.6 on 2021-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('smile', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='categories',
            field=models.ManyToManyField(blank=True, to='bot.Category'),
        ),
    ]
